"""empty message

Revision ID: 637580d6268d
Revises: eec2a7bd09e4
Create Date: 2023-04-14 13:02:31.054982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637580d6268d'
down_revision = 'eec2a7bd09e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email', 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
